api = "0.8"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime"
  id = "paketo-buildpacks/dotnet-core-aspnet-runtime"
  keywords = ["dotnet", "ASP.NET", "runtime"]
  name = "Paketo Buildpack for ASP.NET Core Runtime"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.configurations]]
    build = true
    description = "specify a version of ASP.NET Runtime to use"
    name = "BP_DOTNET_RUNTIME_VERSION"

  [[metadata.configurations]]
    build = true
    description = "set to 'Disable' to prevent ASP.NET version roll-forward"
    name = "BP_DOTNET_ROLL_FORWARD"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:4f948af91423636c8a8bbd9ad2f9e2b5997b84e84ef36707e3e3250eeb4f00d0bc98ed1442151d1913ba21bb0475ba2adb2d6d6328a93dbe7105f2c0bca2abc9"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.27:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.27?checksum=4f948af91423636c8a8bbd9ad2f9e2b5997b84e84ef36707e3e3250eeb4f00d0bc98ed1442151d1913ba21bb0475ba2adb2d6d6328a93dbe7105f2c0bca2abc9&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.27/aspnetcore-runtime-8.0.27-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.27/aspnetcore-runtime-8.0.27-linux-x64.tar.gz"
    source-checksum = "sha512:4f948af91423636c8a8bbd9ad2f9e2b5997b84e84ef36707e3e3250eeb4f00d0bc98ed1442151d1913ba21bb0475ba2adb2d6d6328a93dbe7105f2c0bca2abc9"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.27/aspnetcore-runtime-8.0.27-linux-x64.tar.gz"
    version = "8.0.27"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:5f76d6183e4d5d90f8672abc865436606ed551593a75771e56b3521797a48dadd6f6de1ff93c2624662ac59795a7ce8acd7298c5de889b198b106d7a79b8c114"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.27:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.27?checksum=5f76d6183e4d5d90f8672abc865436606ed551593a75771e56b3521797a48dadd6f6de1ff93c2624662ac59795a7ce8acd7298c5de889b198b106d7a79b8c114&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.27/aspnetcore-runtime-8.0.27-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.27/aspnetcore-runtime-8.0.27-linux-arm64.tar.gz"
    source-checksum = "sha512:5f76d6183e4d5d90f8672abc865436606ed551593a75771e56b3521797a48dadd6f6de1ff93c2624662ac59795a7ce8acd7298c5de889b198b106d7a79b8c114"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.27/aspnetcore-runtime-8.0.27-linux-arm64.tar.gz"
    version = "8.0.27"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:3052101724895dbc18beca8fa939c29185678fef7fb0798a2bad948761c61c172044500395315f9f2bd7c7343a14a9e8a438e5b841df3a7dc3b77faa5c263bd6"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.28:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.28?checksum=3052101724895dbc18beca8fa939c29185678fef7fb0798a2bad948761c61c172044500395315f9f2bd7c7343a14a9e8a438e5b841df3a7dc3b77faa5c263bd6&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.28/aspnetcore-runtime-8.0.28-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.28/aspnetcore-runtime-8.0.28-linux-x64.tar.gz"
    source-checksum = "sha512:3052101724895dbc18beca8fa939c29185678fef7fb0798a2bad948761c61c172044500395315f9f2bd7c7343a14a9e8a438e5b841df3a7dc3b77faa5c263bd6"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.28/aspnetcore-runtime-8.0.28-linux-x64.tar.gz"
    version = "8.0.28"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:28cdefc13f4169b6348cb3203bbb9d7b1723c513ee44ea52fcb6aac5c1e7986099141815b52451320f4c703edb8b11d675213e6c013138baae6f80ace9d93477"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.28:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.28?checksum=28cdefc13f4169b6348cb3203bbb9d7b1723c513ee44ea52fcb6aac5c1e7986099141815b52451320f4c703edb8b11d675213e6c013138baae6f80ace9d93477&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.28/aspnetcore-runtime-8.0.28-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.28/aspnetcore-runtime-8.0.28-linux-arm64.tar.gz"
    source-checksum = "sha512:28cdefc13f4169b6348cb3203bbb9d7b1723c513ee44ea52fcb6aac5c1e7986099141815b52451320f4c703edb8b11d675213e6c013138baae6f80ace9d93477"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.28/aspnetcore-runtime-8.0.28-linux-arm64.tar.gz"
    version = "8.0.28"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:00c0c73a5d3ca5607d8e1db020409a201bcb42469e4e4f7fb992a99e8a8efa41657e8c2bd29c99cc1f97331d0b47bb75256479d9453649621a3aca18a202f48e"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.16:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.16?checksum=00c0c73a5d3ca5607d8e1db020409a201bcb42469e4e4f7fb992a99e8a8efa41657e8c2bd29c99cc1f97331d0b47bb75256479d9453649621a3aca18a202f48e&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.16/aspnetcore-runtime-9.0.16-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.16/aspnetcore-runtime-9.0.16-linux-x64.tar.gz"
    source-checksum = "sha512:00c0c73a5d3ca5607d8e1db020409a201bcb42469e4e4f7fb992a99e8a8efa41657e8c2bd29c99cc1f97331d0b47bb75256479d9453649621a3aca18a202f48e"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.16/aspnetcore-runtime-9.0.16-linux-x64.tar.gz"
    version = "9.0.16"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:85f241cf89b8f6fb1f97b452e10d19e2f021f9e595eedd342ddfed8a3a53596a5283e1b6b5e49e7e1d67c2a03cfa52615835e3c7cf00639ed40b082c4e429dff"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.16:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.16?checksum=85f241cf89b8f6fb1f97b452e10d19e2f021f9e595eedd342ddfed8a3a53596a5283e1b6b5e49e7e1d67c2a03cfa52615835e3c7cf00639ed40b082c4e429dff&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.16/aspnetcore-runtime-9.0.16-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.16/aspnetcore-runtime-9.0.16-linux-arm64.tar.gz"
    source-checksum = "sha512:85f241cf89b8f6fb1f97b452e10d19e2f021f9e595eedd342ddfed8a3a53596a5283e1b6b5e49e7e1d67c2a03cfa52615835e3c7cf00639ed40b082c4e429dff"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.16/aspnetcore-runtime-9.0.16-linux-arm64.tar.gz"
    version = "9.0.16"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:a800b47a7db2bebd418a77553b232f9a30a7d1e3da0e7b07572878ac3a75cfa8317f7c969ab78b79acc2e8cbacea5467566d4108def115b3f2659377660aab8a"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.17:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.17?checksum=a800b47a7db2bebd418a77553b232f9a30a7d1e3da0e7b07572878ac3a75cfa8317f7c969ab78b79acc2e8cbacea5467566d4108def115b3f2659377660aab8a&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.17/aspnetcore-runtime-9.0.17-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.17/aspnetcore-runtime-9.0.17-linux-x64.tar.gz"
    source-checksum = "sha512:a800b47a7db2bebd418a77553b232f9a30a7d1e3da0e7b07572878ac3a75cfa8317f7c969ab78b79acc2e8cbacea5467566d4108def115b3f2659377660aab8a"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.17/aspnetcore-runtime-9.0.17-linux-x64.tar.gz"
    version = "9.0.17"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:6ca04293c246b1485e7db51e743c53336d87b8e92c6ab8992d6d0972de84fed0adb3c743fafca58508199cad01f0cea875317d7b0cd977a82cab7d37c67c190b"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.17:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.17?checksum=6ca04293c246b1485e7db51e743c53336d87b8e92c6ab8992d6d0972de84fed0adb3c743fafca58508199cad01f0cea875317d7b0cd977a82cab7d37c67c190b&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.17/aspnetcore-runtime-9.0.17-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.17/aspnetcore-runtime-9.0.17-linux-arm64.tar.gz"
    source-checksum = "sha512:6ca04293c246b1485e7db51e743c53336d87b8e92c6ab8992d6d0972de84fed0adb3c743fafca58508199cad01f0cea875317d7b0cd977a82cab7d37c67c190b"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.17/aspnetcore-runtime-9.0.17-linux-arm64.tar.gz"
    version = "9.0.17"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:e397fe8522af794b37cb313047fb786c060850a1191d0ec0a1ae248943b3cf515b25650aaf0717981dacda7851e418f3fd90c4c2827b7b6495d3db4bebf1d756"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.8:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.8?checksum=e397fe8522af794b37cb313047fb786c060850a1191d0ec0a1ae248943b3cf515b25650aaf0717981dacda7851e418f3fd90c4c2827b7b6495d3db4bebf1d756&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.8/aspnetcore-runtime-10.0.8-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.8/aspnetcore-runtime-10.0.8-linux-x64.tar.gz"
    source-checksum = "sha512:e397fe8522af794b37cb313047fb786c060850a1191d0ec0a1ae248943b3cf515b25650aaf0717981dacda7851e418f3fd90c4c2827b7b6495d3db4bebf1d756"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.8/aspnetcore-runtime-10.0.8-linux-x64.tar.gz"
    version = "10.0.8"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:4bbdc0586b1b192da43606069b9298927d06527cdc5d61bf4fc401bfd5e0bf4303607dcb09d822df94dcc7f9447486ebb3990593c2e5cbedecc35fe2de37457d"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.8:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.8?checksum=4bbdc0586b1b192da43606069b9298927d06527cdc5d61bf4fc401bfd5e0bf4303607dcb09d822df94dcc7f9447486ebb3990593c2e5cbedecc35fe2de37457d&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.8/aspnetcore-runtime-10.0.8-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.8/aspnetcore-runtime-10.0.8-linux-arm64.tar.gz"
    source-checksum = "sha512:4bbdc0586b1b192da43606069b9298927d06527cdc5d61bf4fc401bfd5e0bf4303607dcb09d822df94dcc7f9447486ebb3990593c2e5cbedecc35fe2de37457d"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.8/aspnetcore-runtime-10.0.8-linux-arm64.tar.gz"
    version = "10.0.8"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:a3d1fc542adfc2532e9a8ac4444fb0539efcec33cf733de60cd5f6f8fe3e9a5a3236b98694b26cf73d9cd75d2e1bca0c691e83d41107debc4cf87a5ab299a82d"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.9:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.9?checksum=a3d1fc542adfc2532e9a8ac4444fb0539efcec33cf733de60cd5f6f8fe3e9a5a3236b98694b26cf73d9cd75d2e1bca0c691e83d41107debc4cf87a5ab299a82d&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.9/aspnetcore-runtime-10.0.9-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.9/aspnetcore-runtime-10.0.9-linux-x64.tar.gz"
    source-checksum = "sha512:a3d1fc542adfc2532e9a8ac4444fb0539efcec33cf733de60cd5f6f8fe3e9a5a3236b98694b26cf73d9cd75d2e1bca0c691e83d41107debc4cf87a5ab299a82d"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.9/aspnetcore-runtime-10.0.9-linux-x64.tar.gz"
    version = "10.0.9"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:13377eca63d52a85b7e7126f0ad6b017ffbd520b6d95db0ba05eb6c152645ef4238f8a3744d2b04ac418d9856ee7db732be927aabde84871402c3548e1ffcee2"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.9:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.9?checksum=13377eca63d52a85b7e7126f0ad6b017ffbd520b6d95db0ba05eb6c152645ef4238f8a3744d2b04ac418d9856ee7db732be927aabde84871402c3548e1ffcee2&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.9/aspnetcore-runtime-10.0.9-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.9/aspnetcore-runtime-10.0.9-linux-arm64.tar.gz"
    source-checksum = "sha512:13377eca63d52a85b7e7126f0ad6b017ffbd520b6d95db0ba05eb6c152645ef4238f8a3744d2b04ac418d9856ee7db732be927aabde84871402c3548e1ffcee2"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.9/aspnetcore-runtime-10.0.9-linux-arm64.tar.gz"
    version = "10.0.9"

  [[metadata.dependency-constraints]]
    constraint = "8.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "9.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "10.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
