api = "0.8"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime"
  id = "paketo-buildpacks/dotnet-core-aspnet-runtime"
  keywords = ["dotnet", "ASP.NET", "runtime"]
  name = "Paketo Buildpack for ASP.NET Core Runtime"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.configurations]]
    build = true
    description = "specify a version of ASP.NET Runtime to use"
    name = "BP_DOTNET_RUNTIME_VERSION"

  [[metadata.configurations]]
    build = true
    description = "set to 'Disable' to prevent ASP.NET version roll-forward"
    name = "BP_DOTNET_ROLL_FORWARD"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:e785fe2a7b06a56a0070862d4fbf41df0e1c04b89a76f4cca2d75de320642274ccc49cdd79dd6d781b504e5631e2f25b0b3566474b9f4b347a929d8b176483de"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.23:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.23?checksum=e785fe2a7b06a56a0070862d4fbf41df0e1c04b89a76f4cca2d75de320642274ccc49cdd79dd6d781b504e5631e2f25b0b3566474b9f4b347a929d8b176483de&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-x64.tar.gz"
    source-checksum = "sha512:e785fe2a7b06a56a0070862d4fbf41df0e1c04b89a76f4cca2d75de320642274ccc49cdd79dd6d781b504e5631e2f25b0b3566474b9f4b347a929d8b176483de"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-x64.tar.gz"
    version = "8.0.23"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:c237c886b328a8b79fa6e341590ec6739325450d3f10be9c26bf908e4e1082b03bdf389ab794318187bb4694f261f87e3d4b466017b21980ffe7b4d70d028bb9"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.23:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.23?checksum=c237c886b328a8b79fa6e341590ec6739325450d3f10be9c26bf908e4e1082b03bdf389ab794318187bb4694f261f87e3d4b466017b21980ffe7b4d70d028bb9&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-arm64.tar.gz"
    source-checksum = "sha512:c237c886b328a8b79fa6e341590ec6739325450d3f10be9c26bf908e4e1082b03bdf389ab794318187bb4694f261f87e3d4b466017b21980ffe7b4d70d028bb9"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.23/aspnetcore-runtime-8.0.23-linux-arm64.tar.gz"
    version = "8.0.23"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:9a5cb25990649fc1c75675e94e2e4699dfc5979a99a2eec36babb240ca5278f1ac2552ecfec16834449ac3d5482a0fd303ac4ba53ca4749fabfb2b0194ba4635"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.24:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.24?checksum=9a5cb25990649fc1c75675e94e2e4699dfc5979a99a2eec36babb240ca5278f1ac2552ecfec16834449ac3d5482a0fd303ac4ba53ca4749fabfb2b0194ba4635&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.24/aspnetcore-runtime-8.0.24-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.24/aspnetcore-runtime-8.0.24-linux-x64.tar.gz"
    source-checksum = "sha512:9a5cb25990649fc1c75675e94e2e4699dfc5979a99a2eec36babb240ca5278f1ac2552ecfec16834449ac3d5482a0fd303ac4ba53ca4749fabfb2b0194ba4635"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.24/aspnetcore-runtime-8.0.24-linux-x64.tar.gz"
    version = "8.0.24"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:e269491953c552ecfd31e620052eec84e60b28da39ce06c2d64c322da9a164a6c896a1da9bf965df78e6dfdec6ab9e42ad5c36b2c641d6ea05a5243930a6391c"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.24:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.24?checksum=e269491953c552ecfd31e620052eec84e60b28da39ce06c2d64c322da9a164a6c896a1da9bf965df78e6dfdec6ab9e42ad5c36b2c641d6ea05a5243930a6391c&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.24/aspnetcore-runtime-8.0.24-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.24/aspnetcore-runtime-8.0.24-linux-arm64.tar.gz"
    source-checksum = "sha512:e269491953c552ecfd31e620052eec84e60b28da39ce06c2d64c322da9a164a6c896a1da9bf965df78e6dfdec6ab9e42ad5c36b2c641d6ea05a5243930a6391c"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.24/aspnetcore-runtime-8.0.24-linux-arm64.tar.gz"
    version = "8.0.24"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:489b8077f2661eaebe421140774b0769519c4963a4bb2fe7d5eff72c99b29a81d5ac6684707449a0ff889a074b6ee58fb4d00a346b859fb75d1d5470e8fb9296"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.12:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.12?checksum=489b8077f2661eaebe421140774b0769519c4963a4bb2fe7d5eff72c99b29a81d5ac6684707449a0ff889a074b6ee58fb4d00a346b859fb75d1d5470e8fb9296&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-x64.tar.gz"
    source-checksum = "sha512:489b8077f2661eaebe421140774b0769519c4963a4bb2fe7d5eff72c99b29a81d5ac6684707449a0ff889a074b6ee58fb4d00a346b859fb75d1d5470e8fb9296"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-x64.tar.gz"
    version = "9.0.12"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:9459fd465ac014188b440e0dd785427e3538224d37578a4734382e2a7069c0d87014eb07e98309386e195b4487536f8d8ccb126f7178f2e2521ac934bf63de6d"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.12:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.12?checksum=9459fd465ac014188b440e0dd785427e3538224d37578a4734382e2a7069c0d87014eb07e98309386e195b4487536f8d8ccb126f7178f2e2521ac934bf63de6d&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-arm64.tar.gz"
    source-checksum = "sha512:9459fd465ac014188b440e0dd785427e3538224d37578a4734382e2a7069c0d87014eb07e98309386e195b4487536f8d8ccb126f7178f2e2521ac934bf63de6d"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.12/aspnetcore-runtime-9.0.12-linux-arm64.tar.gz"
    version = "9.0.12"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:9f4895d2479fa91dc8007e089ad861de989e52455a93cee19de0bd0607cce4ae00c542742527f76d3be55ff1d4790064775095f582e46bde68f8d714b021b624"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.13:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.13?checksum=9f4895d2479fa91dc8007e089ad861de989e52455a93cee19de0bd0607cce4ae00c542742527f76d3be55ff1d4790064775095f582e46bde68f8d714b021b624&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.13/aspnetcore-runtime-9.0.13-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.13/aspnetcore-runtime-9.0.13-linux-x64.tar.gz"
    source-checksum = "sha512:9f4895d2479fa91dc8007e089ad861de989e52455a93cee19de0bd0607cce4ae00c542742527f76d3be55ff1d4790064775095f582e46bde68f8d714b021b624"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.13/aspnetcore-runtime-9.0.13-linux-x64.tar.gz"
    version = "9.0.13"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:6a80ccbadb5dec1df3e584cf99b454f8bf55ac0da432f4facfd01a5e023e5c56e4e3c53d83aa98e39242d9d72d05775a7661dee78f77bb9dcb841205cfd7080c"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.13:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.13?checksum=6a80ccbadb5dec1df3e584cf99b454f8bf55ac0da432f4facfd01a5e023e5c56e4e3c53d83aa98e39242d9d72d05775a7661dee78f77bb9dcb841205cfd7080c&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.13/aspnetcore-runtime-9.0.13-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.13/aspnetcore-runtime-9.0.13-linux-arm64.tar.gz"
    source-checksum = "sha512:6a80ccbadb5dec1df3e584cf99b454f8bf55ac0da432f4facfd01a5e023e5c56e4e3c53d83aa98e39242d9d72d05775a7661dee78f77bb9dcb841205cfd7080c"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.13/aspnetcore-runtime-9.0.13-linux-arm64.tar.gz"
    version = "9.0.13"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:41ecfe6a6ef9e587a58f1336fe667e90585f0bca2227e25d0de9340c634967b180ef8c7c93a61fe390949a9fddc1e656ba717bc132f6947e6e450fcfc4966020"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.2:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.2?checksum=41ecfe6a6ef9e587a58f1336fe667e90585f0bca2227e25d0de9340c634967b180ef8c7c93a61fe390949a9fddc1e656ba717bc132f6947e6e450fcfc4966020&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-x64.tar.gz"
    source-checksum = "sha512:41ecfe6a6ef9e587a58f1336fe667e90585f0bca2227e25d0de9340c634967b180ef8c7c93a61fe390949a9fddc1e656ba717bc132f6947e6e450fcfc4966020"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-x64.tar.gz"
    version = "10.0.2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:52ec81492d6d4253c00d7f51f12d5fddb10252ce664db020c4a90e4433e7eb7862529737400d5862f6fba41cb2bcf223f802e01d194b82908ce84530b03800b1"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.2:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.2?checksum=52ec81492d6d4253c00d7f51f12d5fddb10252ce664db020c4a90e4433e7eb7862529737400d5862f6fba41cb2bcf223f802e01d194b82908ce84530b03800b1&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-arm64.tar.gz"
    source-checksum = "sha512:52ec81492d6d4253c00d7f51f12d5fddb10252ce664db020c4a90e4433e7eb7862529737400d5862f6fba41cb2bcf223f802e01d194b82908ce84530b03800b1"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.2/aspnetcore-runtime-10.0.2-linux-arm64.tar.gz"
    version = "10.0.2"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:a4bcf75a734c72ab87f356eeabfdbcc01212d1fa4629bf2ccdf8fa1cd9e9236daf0fb63499afa5923de56593aae57038283ffb518c6753a20b34552529a11c37"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.3:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.3?checksum=a4bcf75a734c72ab87f356eeabfdbcc01212d1fa4629bf2ccdf8fa1cd9e9236daf0fb63499afa5923de56593aae57038283ffb518c6753a20b34552529a11c37&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.3/aspnetcore-runtime-10.0.3-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.3/aspnetcore-runtime-10.0.3-linux-x64.tar.gz"
    source-checksum = "sha512:a4bcf75a734c72ab87f356eeabfdbcc01212d1fa4629bf2ccdf8fa1cd9e9236daf0fb63499afa5923de56593aae57038283ffb518c6753a20b34552529a11c37"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.3/aspnetcore-runtime-10.0.3-linux-x64.tar.gz"
    version = "10.0.3"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:6c174c466dbc495bac6a6ba9dae99cdd5185999dc91eca9db540ca424a294a43d47994c4cb5b59bc125451ce4d5670683df39e2f9af2f0f0b4547a810f95ffd3"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.3:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.3?checksum=6c174c466dbc495bac6a6ba9dae99cdd5185999dc91eca9db540ca424a294a43d47994c4cb5b59bc125451ce4d5670683df39e2f9af2f0f0b4547a810f95ffd3&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.3/aspnetcore-runtime-10.0.3-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.3/aspnetcore-runtime-10.0.3-linux-arm64.tar.gz"
    source-checksum = "sha512:6c174c466dbc495bac6a6ba9dae99cdd5185999dc91eca9db540ca424a294a43d47994c4cb5b59bc125451ce4d5670683df39e2f9af2f0f0b4547a810f95ffd3"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.3/aspnetcore-runtime-10.0.3-linux-arm64.tar.gz"
    version = "10.0.3"

  [[metadata.dependency-constraints]]
    constraint = "8.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "9.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "10.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
