api = "0.8"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime"
  id = "paketo-buildpacks/dotnet-core-aspnet-runtime"
  keywords = ["dotnet", "ASP.NET", "runtime"]
  name = "Paketo Buildpack for ASP.NET Core Runtime"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet-runtime/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.configurations]]
    build = true
    description = "specify a version of ASP.NET Runtime to use"
    name = "BP_DOTNET_RUNTIME_VERSION"

  [[metadata.configurations]]
    build = true
    description = "set to 'Disable' to prevent ASP.NET version roll-forward"
    name = "BP_DOTNET_ROLL_FORWARD"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:ddb66ac366252ab382271241b3e53a75201d2c848c9ec870a27fb178a6db18e4d949b9896a3d8530d03d255f4fd51d635367bedda3d9f3c677cb596784dbcb9c"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.25:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.25?checksum=ddb66ac366252ab382271241b3e53a75201d2c848c9ec870a27fb178a6db18e4d949b9896a3d8530d03d255f4fd51d635367bedda3d9f3c677cb596784dbcb9c&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.25/aspnetcore-runtime-8.0.25-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.25/aspnetcore-runtime-8.0.25-linux-x64.tar.gz"
    source-checksum = "sha512:ddb66ac366252ab382271241b3e53a75201d2c848c9ec870a27fb178a6db18e4d949b9896a3d8530d03d255f4fd51d635367bedda3d9f3c677cb596784dbcb9c"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.25/aspnetcore-runtime-8.0.25-linux-x64.tar.gz"
    version = "8.0.25"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:65d8b16bbef90c44daac906aaf92818f43a8482191dbf3f20bddcdd1ad6077d17b6178364bd08249501ddd3021a4c8f5f98a1c0360e126870db14cf06cd12727"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.25:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.25?checksum=65d8b16bbef90c44daac906aaf92818f43a8482191dbf3f20bddcdd1ad6077d17b6178364bd08249501ddd3021a4c8f5f98a1c0360e126870db14cf06cd12727&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.25/aspnetcore-runtime-8.0.25-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.25/aspnetcore-runtime-8.0.25-linux-arm64.tar.gz"
    source-checksum = "sha512:65d8b16bbef90c44daac906aaf92818f43a8482191dbf3f20bddcdd1ad6077d17b6178364bd08249501ddd3021a4c8f5f98a1c0360e126870db14cf06cd12727"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.25/aspnetcore-runtime-8.0.25-linux-arm64.tar.gz"
    version = "8.0.25"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:2a5d39bfdb2d734fd765f806bf4be6138bc8d9b44f2f8aee3250ced56eaad4c0e4bf06141dec6ef2c6a46a8faf3d8ffd60b7361b687ff7d8b45179df35bb0149"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.26:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.26?checksum=2a5d39bfdb2d734fd765f806bf4be6138bc8d9b44f2f8aee3250ced56eaad4c0e4bf06141dec6ef2c6a46a8faf3d8ffd60b7361b687ff7d8b45179df35bb0149&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.26/aspnetcore-runtime-8.0.26-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.26/aspnetcore-runtime-8.0.26-linux-x64.tar.gz"
    source-checksum = "sha512:2a5d39bfdb2d734fd765f806bf4be6138bc8d9b44f2f8aee3250ced56eaad4c0e4bf06141dec6ef2c6a46a8faf3d8ffd60b7361b687ff7d8b45179df35bb0149"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.26/aspnetcore-runtime-8.0.26-linux-x64.tar.gz"
    version = "8.0.26"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:93969f80c4bffa276a5538a5133e20ea8afd59b7f83f932cd0749ff37332f85ca3e3e9e90fb45ec8e2fd1a814df373b617565808823113e2911f5b55d018d19c"
    cpe = "cpe:2.3:a:microsoft:.net:8.0.26:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@8.0.26?checksum=93969f80c4bffa276a5538a5133e20ea8afd59b7f83f932cd0749ff37332f85ca3e3e9e90fb45ec8e2fd1a814df373b617565808823113e2911f5b55d018d19c&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.26/aspnetcore-runtime-8.0.26-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.26/aspnetcore-runtime-8.0.26-linux-arm64.tar.gz"
    source-checksum = "sha512:93969f80c4bffa276a5538a5133e20ea8afd59b7f83f932cd0749ff37332f85ca3e3e9e90fb45ec8e2fd1a814df373b617565808823113e2911f5b55d018d19c"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.26/aspnetcore-runtime-8.0.26-linux-arm64.tar.gz"
    version = "8.0.26"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:6d0947390f9ec316297f21a9ec022528a27205a44328f9417fb8675783edc56022e5e15ea65650c5e73cb73917c09c52305d3e85e4c12acd5e11074871bb0679"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.14:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.14?checksum=6d0947390f9ec316297f21a9ec022528a27205a44328f9417fb8675783edc56022e5e15ea65650c5e73cb73917c09c52305d3e85e4c12acd5e11074871bb0679&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.14/aspnetcore-runtime-9.0.14-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.14/aspnetcore-runtime-9.0.14-linux-x64.tar.gz"
    source-checksum = "sha512:6d0947390f9ec316297f21a9ec022528a27205a44328f9417fb8675783edc56022e5e15ea65650c5e73cb73917c09c52305d3e85e4c12acd5e11074871bb0679"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.14/aspnetcore-runtime-9.0.14-linux-x64.tar.gz"
    version = "9.0.14"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:c5cd05971c9cba0c211ceb55e226cbfb62f172db8345fa5d4e476a4ccb3a4f61d6e51dc2b2d178eb55f3673ad2d61cf72ae649fb84ccf2c3dbbbd4acdbb78132"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.14:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.14?checksum=c5cd05971c9cba0c211ceb55e226cbfb62f172db8345fa5d4e476a4ccb3a4f61d6e51dc2b2d178eb55f3673ad2d61cf72ae649fb84ccf2c3dbbbd4acdbb78132&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.14/aspnetcore-runtime-9.0.14-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.14/aspnetcore-runtime-9.0.14-linux-arm64.tar.gz"
    source-checksum = "sha512:c5cd05971c9cba0c211ceb55e226cbfb62f172db8345fa5d4e476a4ccb3a4f61d6e51dc2b2d178eb55f3673ad2d61cf72ae649fb84ccf2c3dbbbd4acdbb78132"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.14/aspnetcore-runtime-9.0.14-linux-arm64.tar.gz"
    version = "9.0.14"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:85d474b303fb8f1867125d9aa1ec39db5afff179b165287e45fd78b7ec51d414e5937871bda5948b8e750afe9c220afe6138eba7108090bfba1e5dad93d39c4e"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.15:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.15?checksum=85d474b303fb8f1867125d9aa1ec39db5afff179b165287e45fd78b7ec51d414e5937871bda5948b8e750afe9c220afe6138eba7108090bfba1e5dad93d39c4e&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.15/aspnetcore-runtime-9.0.15-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.15/aspnetcore-runtime-9.0.15-linux-x64.tar.gz"
    source-checksum = "sha512:85d474b303fb8f1867125d9aa1ec39db5afff179b165287e45fd78b7ec51d414e5937871bda5948b8e750afe9c220afe6138eba7108090bfba1e5dad93d39c4e"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.15/aspnetcore-runtime-9.0.15-linux-x64.tar.gz"
    version = "9.0.15"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:72b9f4b0649e5a3b874597c1b50dbbb246831e933455bbe34c3c53ffdd3016eca7d42090c6d785bb9dae78b9f34d37757df2b430f6309d811c08df6839ce00cf"
    cpe = "cpe:2.3:a:microsoft:.net:9.0.15:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-10T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@9.0.15?checksum=72b9f4b0649e5a3b874597c1b50dbbb246831e933455bbe34c3c53ffdd3016eca7d42090c6d785bb9dae78b9f34d37757df2b430f6309d811c08df6839ce00cf&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.15/aspnetcore-runtime-9.0.15-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.15/aspnetcore-runtime-9.0.15-linux-arm64.tar.gz"
    source-checksum = "sha512:72b9f4b0649e5a3b874597c1b50dbbb246831e933455bbe34c3c53ffdd3016eca7d42090c6d785bb9dae78b9f34d37757df2b430f6309d811c08df6839ce00cf"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.15/aspnetcore-runtime-9.0.15-linux-arm64.tar.gz"
    version = "9.0.15"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:89eeb16d1971dc0a854754a3bc4cebb637a959c889f56216af292580b76fbff01c329dd0933896b74ef6a2d4bc56b9c4bb605196d5c0520ca43027421d155365"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.6:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.6?checksum=89eeb16d1971dc0a854754a3bc4cebb637a959c889f56216af292580b76fbff01c329dd0933896b74ef6a2d4bc56b9c4bb605196d5c0520ca43027421d155365&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.6/aspnetcore-runtime-10.0.6-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.6/aspnetcore-runtime-10.0.6-linux-x64.tar.gz"
    source-checksum = "sha512:89eeb16d1971dc0a854754a3bc4cebb637a959c889f56216af292580b76fbff01c329dd0933896b74ef6a2d4bc56b9c4bb605196d5c0520ca43027421d155365"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.6/aspnetcore-runtime-10.0.6-linux-x64.tar.gz"
    version = "10.0.6"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:8dee4e65a4a76e833867616df508a39c2f8a710269a2361e47acb73d09080e50405c1d84206327ff5df127a9f206451b0cedf1451d43144e440d9c4e350e9497"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.6:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.6?checksum=8dee4e65a4a76e833867616df508a39c2f8a710269a2361e47acb73d09080e50405c1d84206327ff5df127a9f206451b0cedf1451d43144e440d9c4e350e9497&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.6/aspnetcore-runtime-10.0.6-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.6/aspnetcore-runtime-10.0.6-linux-arm64.tar.gz"
    source-checksum = "sha512:8dee4e65a4a76e833867616df508a39c2f8a710269a2361e47acb73d09080e50405c1d84206327ff5df127a9f206451b0cedf1451d43144e440d9c4e350e9497"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.6/aspnetcore-runtime-10.0.6-linux-arm64.tar.gz"
    version = "10.0.6"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha512:378a24fb4327275e0a46039bd3719b02d2d6b1c7bf4b0ebcabc4dd6c65a818c897790b8a0b7fa1712b021c4dd0a97f995fe6037fa92b2e909e43266501d6cf1a"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.7:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.7?checksum=378a24fb4327275e0a46039bd3719b02d2d6b1c7bf4b0ebcabc4dd6c65a818c897790b8a0b7fa1712b021c4dd0a97f995fe6037fa92b2e909e43266501d6cf1a&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.7/aspnetcore-runtime-10.0.7-linux-x64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.7/aspnetcore-runtime-10.0.7-linux-x64.tar.gz"
    source-checksum = "sha512:378a24fb4327275e0a46039bd3719b02d2d6b1c7bf4b0ebcabc4dd6c65a818c897790b8a0b7fa1712b021c4dd0a97f995fe6037fa92b2e909e43266501d6cf1a"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.7/aspnetcore-runtime-10.0.7-linux-x64.tar.gz"
    version = "10.0.7"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha512:e7a175641becee2e6defa97ddb96261d53137eed485c62f5e367960bdd0b012f718551d277eabe606efcfc2275601fba4b499e90ba71bbab23c50eff688f9f6f"
    cpe = "cpe:2.3:a:microsoft:.net:10.0.7:*:*:*:*:*:*:*"
    deprecation_date = "2028-11-14T00:00:00Z"
    id = "dotnet-core-aspnet-runtime"
    licenses = ["MIT", "MIT-0"]
    name = "ASP.NET Core Runtime"
    os = "linux"
    purl = "pkg:generic/dotnet-core-aspnet-runtime@10.0.7?checksum=e7a175641becee2e6defa97ddb96261d53137eed485c62f5e367960bdd0b012f718551d277eabe606efcfc2275601fba4b499e90ba71bbab23c50eff688f9f6f&download_url=https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.7/aspnetcore-runtime-10.0.7-linux-arm64.tar.gz"
    source = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.7/aspnetcore-runtime-10.0.7-linux-arm64.tar.gz"
    source-checksum = "sha512:e7a175641becee2e6defa97ddb96261d53137eed485c62f5e367960bdd0b012f718551d277eabe606efcfc2275601fba4b499e90ba71bbab23c50eff688f9f6f"
    stacks = ["*"]
    uri = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/10.0.7/aspnetcore-runtime-10.0.7-linux-arm64.tar.gz"
    version = "10.0.7"

  [[metadata.dependency-constraints]]
    constraint = "8.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "9.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "10.0.*"
    id = "dotnet-core-aspnet-runtime"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
